name: 'build and deploy test server'
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  build:
    name: 'Build & Publish'
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
        
      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v1
        
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1

      - name: "Login to GitHub Registry"
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: "vanitoo"
          password: ${{ secrets.REGISTRY_TOKEN }}
          
      - name: "Build&Deploy template-server"
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/dockertest:${{ github.event.release.tag_name }}
            ghcr.io/${{ github.repository_owner }}/dockertest:latest
          secrets: |
            "ASPNETCORE_ENVIRONMENT=Release"
          build-args: |
            build_mode=Release
            
      - name: "Build&Deploy template-nginx"
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/dockertest:${{ github.event.release.tag_name }}
            ghcr.io/${{ github.repository_owner }}/dockertest:latest
          build-args: |
            build_mode=Release

      - name: "Run deploy on server"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo docker-compose -f docker-compose.yml -p prod pull
            sudo docker-compose -f docker-compose.yml -p prod up -d
            
