name: Example Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 0_Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Example Step
        run: |
          echo "This is an example step."
          echo  GIT_TOKEN
        env:
          GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
